paginate: 6
paginate_path: "page:num"
markdown_ext:  markdown,mkd,mkdn,md
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]